# Generated by Django 3.2.3 on 2021-06-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='timeline_description',
        ),
        migrations.AddField(
            model_name='survey',
            name='timeline_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
