# Generated by Django 3.2.3 on 2021-06-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20210601_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='access_freq',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='survey',
            name='roadblocks',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='survey',
            name='startup_stage',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tech_challenge',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tech_exp',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tech_founder',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='survey',
            name='timeline',
            field=models.CharField(max_length=50),
        ),
    ]
